# -*- coding: utf-8 -*-
from setuptools import setup

package_dir = {"": "python"}

packages = ["lvmagp", "lvmagp.actor", "lvmagp.actor.commands"]

package_data = {"": ["*"], "lvmagp": ["etc/*"]}

install_requires = [
    "click-default-group>=1.2.2,<2.0.0",
    "click>=8.0.1,<9.0.0",
    "sdss-access>=0.2.3",
    "sdss-tree>=2.15.2",
    "sdsstools>=0.4.0",
]

entry_points = {"console_scripts": ["lvmagp = lvmagp.__main__:lvmagp"]}

setup_kwargs = {
    "name": "sdss-lvmagp",
    "version": "0.1.0a0",
    "description": "Simple Template package for creating SDSS Python projects",
    "long_description": "# lvmagp\n\n![Versions](https://img.shields.io/badge/python->3.7-blue)\n[![Documentation Status](https://readthedocs.org/projects/sdss-lvmagp/badge/?version=latest)](https://sdss-lvmagp.readthedocs.io/en/latest/?badge=latest)\n[![Travis (.org)](https://img.shields.io/travis/sdss/lvmagp)](https://travis-ci.org/sdss/lvmagp)\n[![codecov](https://codecov.io/gh/sdss/lvmagp/branch/main/graph/badge.svg)](https://codecov.io/gh/sdss/lvmagp)\n\n<<<<<<< HEAD\nsSimple Template package for creating SDSS Python projects\n=======\nSimple Template package for creating SDSS Python projects\nKHU IRLAB TCS/AGP team \n>>>>>>> 0da89c72a6050bdbc1f726e247b8f9b5200b5f72\n",
    "author": "sumin lee",
    "author_email": "lxmark888@khu.ac.kr",
    "maintainer": None,
    "maintainer_email": None,
    "url": "https://github.com/sdss/lvmagp",
    "package_dir": package_dir,
    "packages": packages,
    "package_data": package_data,
    "install_requires": install_requires,
    "entry_points": entry_points,
    "python_requires": ">=3.7,<4.0",
}
from build import *

build(setup_kwargs)

setup(**setup_kwargs)

# This setup.py was autogenerated using poetry.
